name: "Sync file to AWS S3"
description: "Github action to sync to AWS s3 bucket."
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  AWS_ACCESS_KEY_ID:
    description: "AWS Access Key. [AWS Docs](https://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)"
    required: true
    default: null
  AWS_SECRET_ACCESS_KEY:
    description: "AWS Secret Access Key. [AWS Docs](https://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)"
    required: true
    default: null
  AWS_S3_BUCKET:
    description: "The Name of the S3 Bucket."
    required: true
    default: null
  AWS_REGION:
    description: "Region of the S3 Bucket"
    required: true
    default: null
  SOURCE_DIR:
    description: "Local Directory to Sync/Upload to S3."
    required: false
    defualt: "."
  ARGS:
    description: "s3 comand arguments"
    required: false
    defualt: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.AWS_ACCESS_KEY_ID }}
    - ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    - ${{ inputs.AWS_S3_BUCKET }}
    - ${{ inputs.AWS_REGION }}
    - ${{ inputs.SOURCE_DIR }}
    - ${{ inputs.ARGS }}
